In [70]:
from sentence_transformers import SentenceTransformer
pth = "/mnt/vdb1/BERT_training/sbert_approach/matcher/output/training_paraphrases_-mnt-vdb1-BERT_training-sbert_approach-ckpt_concat_unique_mask-2023-07-06_13-26-34-checkpoint-630000-2023-07-12_07-29-57/48000"

sentences = [name, true_match]#["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer(pth)
embeddings = model.encode(sentences)
print(embeddings)

[[ 1.36942312e-01 -2.35673562e-01 -1.48438923e-02  2.07760204e-02
  -3.89278196e-02  3.26693594e-01 -6.65011942e-01  8.83541226e-01
  -4.20762211e-01  2.22773743e+00  5.32823563e-01 -5.82122684e-01
  -2.82708347e-01  1.83222353e-01 -1.02608457e-01  1.35350183e-01
  -1.33144903e+00 -1.74963400e-01 -3.76902103e-01 -4.86779481e-01
  -4.56262469e-01  2.03941131e+00  4.00249958e-01 -9.71618354e-01
   1.17606187e+00 -1.16707182e+00  6.01641178e-01  1.23495042e+00
  -4.55369707e-03  3.48880410e-01  1.31596482e+00  5.17574608e-01
   6.01133227e-01 -1.20851851e+00 -7.08444118e-01 -1.25377822e+00
  -1.02931714e+00  9.08802032e-01  6.85199022e-01 -2.94770688e-01
  -1.16001463e+00 -2.59222239e-01 -4.85881996e+00 -2.49941766e-01
  -4.02570248e-01 -7.90115073e-02 -1.35626400e+00  1.99150532e-01
  -5.52987099e-01 -4.07016516e-01  2.85677850e-01 -3.51960272e-01
  -4.84921336e-01  4.94996607e-01  1.92116463e+00 -2.78637022e-01
  -7.94942141e-01 -2.24046648e-01  3.87355864e-01  1.35222328e+00
   1.74719

In [71]:
import numpy as np

np.shape(embeddings)

(2, 312)

In [72]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(embeddings[0].reshape(1, -1),embeddings[1].reshape(1, -1))

array([[0.98343986]], dtype=float32)

In [67]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(embeddings[0].reshape(1, -1),embeddings[1].reshape(1, -1))

array([[0.8874818]], dtype=float32)

In [81]:
name = "Чехол (клип-кейс) LuxCase, для Apple iPhone 13 Pro"
false_match = "LuxCase Чехол для APPLE iPhone 13 TPU 1.5mm Tr."
true_match = "LuxCase Защитный чехол для APPLE iPhone 13 Pro"

In [90]:
name = "Чехол (клип-кейс) LuxCase, для Apple iPhone 13 Pro"
false_match = "LuxCase Чехол для APPLE iPhone 13 TPU 1.5mm Tr."
true_match = "LuxCase Защитная пленка для APPLE iPad 13 Pro"

In [96]:
from transformers import AutoTokenizer, AutoModel
import torch


#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


# Sentences we want sentence embeddings for
sentences = ['This is an example sentence', "Each sentence is converted"]#[0]
sentences = [name, false_match]
# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained(pth)
model = AutoModel.from_pretrained(pth)

# Tokenize sentences
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

# Perform pooling. In this case, max pooling.
sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

# print("Sentence embeddings:")
# print(model_output)

In [97]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(model_output[1][0].reshape(1, -1), model_output[1][1].reshape(1, -1))

array([[0.06133906]], dtype=float32)

In [101]:
def cosin_metric(x1, x2):
    return np.dot(x1, x2) / (np.linalg.norm(x1) * np.linalg.norm(x2))

cosin_metric(model_output[1][0], model_output[1][1])

0.061339065

In [74]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(model_output[1][0].reshape(1, -1), model_output[1][1].reshape(1, -1))

array([[0.9872594]], dtype=float32)

In [59]:
np.dot(model_output[1][0], model_output[1][1])

29.09391